export const MODULE_OPTIONS_PROVIDER_KEY = Symbol(
  "ELEPHAS_INTEGRATION_TESTING_OPTIONS"
);

export const TESTING_DATABASE_NAME_PROVIDER_KEY = Symbol(
  "ELEPHAS_INTEGRATION_TESTING_TESTING_DATABASE_NAME"
);
