export const DEFAULT_POOL_PROVIDER_KEY = Symbol("ELEPHAS_DEFAULT_POOL");
export const MODULE_OPTIONS_KEY = Symbol("ELEPHAS_MODULE_OPTIONS");

export const VOID_TYPE_ALIAS_KEY = Symbol("ELEPHAS_VOID");
